# =================================================================================================
# Imports rules from '.github/rulesets' into GitHub's internal configuration.
# Triggered by modifications to this directory on the default branch, or manually.
# =================================================================================================

name: Import Rulesets

on:
  push:
    paths:
      - .github/rulesets/**
  workflow_dispatch:
  workflow_call:

# Cancel in-progress runs when starting a new one.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    # Only respond to changes on the default branch.
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'workflow_call' ||
      github.ref_name == github.event.repository.default_branch
    env:
      RULESETS_DIR: .github/rulesets
    defaults:
      run:
        working-directory: repo

    steps:
      - name: Requirements
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "::error::GH_TOKEN secret is not set." \
              "Create a GitHub Personal Access Token with sufficient access" \
              "and add it as a repository secret named GH_TOKEN."
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Checkout github-rules
        uses: actions/checkout@v4
        with:
          repository: SgtSwagrid/github-rules
          path: github-rules

      - name: Clear
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bash ../github-rules/scripts/clear-rulesets.sh

      - name: Sync
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bash ../github-rules/scripts/import-rulesets.sh
